import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sileo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true, // Le dice a iOS que puede instalarse como App
    title: "Kupo",
    
    // Aquí decides el estilo de la barra superior en iPhone:
    // "default": Fondo blanco con texto negro.
    // "black": Fondo negro con texto blanco.
    // "black-translucent": La app ocupa toda la pantalla por debajo de la hora/batería (estilo nativo moderno).
    statusBarStyle: "black", 
  },
};

export const viewport: Viewport = {
  themeColor: "#09090b", // El color zinc-950 de tu fondo
  width: "device-width",
  initialScale: 1,
  maximumScale: 1, // Evita que la app se haga zoom al tocar inputs en iOS
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="relative z-9999">
            <Toaster 
              options={{
                  fill: "black",
                  styles: {
                      title: 'text-white font-bold',
                      description: 'text-white',
                  },
                  position: 'top-center'
              }}
            />
          </div>
          {children}
        </body>
      </html>
    </>
  );
}
